@startuml domain-models-discussion

left to right direction

skinparam ClassBackgroundColor Ivory
skinparam ClassBorderColor Indigo
skinparam EntityBackgroundColor Ivory
skinparam EntityBorderColor Indigo

title 議論コンテキスト(Discussion Context)

package DiscussionContext as DM #line:Gray {

    entity "参加者" as User << (E, Red) Entity >> #line.bold {
        - userId: UUID
        - username: string
        - email: string
        - password: string
        - icon: file
        - role: string
        --
        + create(): User
        + of(): User
        + reBuild(): User 
        * login()
        * logout()
        * isAuthenticated() 
    }
    note bottom of User
        - 参加者はシステムに登録された個人を表します。
        - 参加者は一意のuserIdで識別され、参加者名、
            メールアドレス、パスワード、アイコンなどの属性を持ちます。
        - username、email、passwordは必須項目です。
    end note

    note top of User
        - 参加者は複数のメイントピックを作成でき、複数の議論に参加できます。
        - 参加者はコメントを投稿したり、サブディスカッションに参加したりすることもできます。
        - 参加者はRoleを持っている。Roleによってリソースにアクセスできる範囲が異なる
    end note

    entity "メイントピック" as MainTopic << (E, Red) Entity >> #line.bold {
        - maintopicId: long
        - title: string
        - description: string
        - createdOn: timestamp
        - image: file
        --
        + create(): MainTopic
        + of(): MainTopic
    }

    note bottom of MainTopic
        - メイントピックは複数の議論とサブトピックを持つことができます。
        - メイントピックは参加者によって作成されます。
        - 参加者はメイントピックを勝手に削除することはできない。
            削除できるのは、アドミンか自身が立てたメイントピックで参加者、閲覧者がいない場合のみ。
        - メイントピックに参加できる人数を制限する可能性があり（検討の余地あり）
    end note

    entity "議論" as Discussion << (E, Red) Entity >> #line.bold {
        - discussionId: long
        - text: string
        - createdOn: timestamp
        - updatedOn: timestamp
        - image: file
        - like: number
        - dislike: number
        --
        + create(): Discussion
        + of(): Discussion
    }

    entity "サブディスカッション" as SubDiscussion << (R, Red) Entity >> #line.bold {
        - subDiscussionId: long
        - text: string
        - createdOn: timestamp
        - updatedOn: timestamp
        - image: file
        - like: number
        - dislike: number
    }

    entity "サブトピック" as SubTopic << (R, Red) Entity >> #line.bold {
        - subTopicId: long
        - title: string
        - description: string
        - image: file
        - createdAt: timestamp
        - favorite: number
        - watch: number
    }

    entity "コメント" as Comment << (R, Red) Entity >> #line.bold {
        - commentId: long
        - text: string
        - image: string
        - createdAt: timestamp
        - like: number
        - dislike: number
    }
}


User "1..*" o--> " 0..*" MainTopic : join
User "1" --> "0..*" Discussion : discuss
MainTopic "1" o--> "0..*" Discussion :has >
MainTopic "1" o--> "0..*" SubTopic : has >
Discussion "1" o---> "0..*" Comment : has >
User "1" ---> "0..*" Comment : comment
SubTopic "1" o---> "0..*" SubDiscussion : has >
User "1" ---> "0..*" SubDiscussion : discuss

@enduml