@startuml domain-models-discussion

left to right direction

skinparam ClassBackgroundColor Ivory
skinparam ClassBorderColor Indigo

title 議論コンテキスト(Discussion Context)

package DiscussionContext as DM #line:Gray {

    class "ユーザー" as User <<Model>> #line.bold {
        - userId: UUID
        - username: string
        - email: string
        - password: string
        - icon: file
        - role: string
        --
        + create(): User
        + of(): User
        + reBuild(): User 
        * login()
        * logout()
        * isAuthenticated() 
    }
    note bottom of User
        - ユーザーはシステムに登録された個人を表します。
        - ユーザーは一意のuserIdで識別され、ユーザー名、
            メールアドレス、パスワード、アイコンなどの属性を持ちます。
        - username、email、passwordは必須項目です。
    end note

    note top of User
        - ユーザーは複数のメイントピックを作成でき、複数の議論に参加できます。
        - ユーザーはコメントを投稿したり、サブディスカッションに参加したりすることもできます。
        - ユーザはRoleを持っている。Roleによってリソースにアクセスできる範囲が異なる
    end note

    class "メイントピック" as MainTopic << Model >> #line.bold {
        - maintopicId: long
        - title: string
        - description: string
        - createdOn: timestamp
        - image: file
        --
        + create(): MainTopic
        + of(): MainTopic
    }

    note bottom of MainTopic
        - メイントピックは複数の議論とサブトピックを持つことができます。
        - メイントピックはユーザーによって作成されます。
        - ユーザはメイントピックを勝手に削除することはできない。
            削除できるのは、アドミンか自身が立てたメイントピックで参加者、閲覧者がいない場合のみ。
        - メイントピックに参加できる人数を制限する可能性があり（検討の余地あり）
    end note

    class "議論" as Discussion << Model >> #line.bold {
        - discussionId: long
        - text: string
        - createdOn: timestamp
        - updatedOn: timestamp
        - image: file
        - like: number
        - dislike: number
        --
        + create(): Discussion
        + of(): Discussion
    }

    class "議論" as SubDiscussion << Model >> #line.bold {
        - subDiscussionId: long
        - text: string
        - createdOn: timestamp
        - updatedOn: timestamp
        - image: file
        - like: number
        - dislike: number
    }

    class "サブトピック" as SubTopic << Model >> #line.bold {
        - subTopicId: long
        - title: string
        - description: string
        - image: file
        - createdAt: timestamp
        - favorite: number
        - watch: number
    }

    class "コメント" as Comment << Model >> #line.bold {
        - commentId: long
        - text: string
        - image: string
        - createdAt: timestamp
        - like: number
        - dislike: number
    }
}


User "1..*" o--> " 0..*" MainTopic : join
User "1" --> "0..*" Discussion : discuss
MainTopic "1" o--> "0..*" Discussion :has >
MainTopic "1" o--> "0..*" SubTopic : has >
Discussion "1" o---> "0..*" Comment : has >
User "1" ---> "0..*" Comment : comment
SubTopic "1" o---> "0..*" SubDiscussion : has >
User "1" ---> "0..*" SubDiscussion : discuss

@enduml